#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenNebula Driver for Linstor
Copyright 2018 LINBIT USA LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from __future__ import print_function

import sys
import xml.etree.ElementTree as ET

from one.extender import clone
from linstor import Resource
from one import consts, driver_action, util


def get_encryption_params(driver):
    encryption_enabled = False
    encryption_passphrase = "DEFAULT_PASSPHRASE"

    try:
        image_root = ET.fromstring(driver.image.xmlstr)
        template_elem = image_root.find("TEMPLATE")

        if template_elem is not None:
            encryption_enabled = template_elem.findtext("ENCRYPTION_ENABLED", encryption_enabled)
            encryption_passphrase = template_elem.findtext("PASSPRHASE", encryption_passphrase)

        return encryption_enabled, encryption_passphrase
    except Exception:
        return encryption_enabled, encryption_passphrase


def main():
    util.log_info("Entering datastore clone")

    arg_driver_action, arg_image_id = util.get_datastore_args()
    driver = driver_action.DriverAction(arg_driver_action)

    res = Resource(
        name="{}-{}".format(consts.IMAGE_PREFIX, driver.image.cloning_id),
        uri=driver.datastore.linstor_controllers
    )

    clone_name = "{}-{}".format(consts.IMAGE_PREFIX, arg_image_id)

    encryption_enabled, encryption_passphrase = get_encryption_params(driver)

    util.log_info("Cloning into new resource '{r}' into resource group '{p}'".format(
        r=clone_name, p=driver.datastore.linstor_resource_group)
    )
    success, _ = clone(
        res,
        clone_name,
        driver.datastore.linstor_resource_group,
        encryption_enabled=encryption_enabled,
        encryption_passphrase=encryption_passphrase
    )

    util.log_info("Exiting datastore clone with " + "success." if success else "error.")

    if success:
        print(clone_name)
    else:
        sys.exit(1)


if __name__ == "__main__":
    util.run_main(main)
